FROM reinaertvdc/alpine:current

RUN apk add --no-cache nginx nginx-mod-http-headers-more nginx-mod-stream
RUN apk add --no-cache tzdata

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
